import React from "react";
import Head from "next/head";
import Layout from "@/components/organisms/Layout";
import { useCallback, useEffect, useState } from "react";
import { savingType } from "@/services/data-types/saving-type";
import { savingService } from "@/services/saving-service";
import Button from "@/components/atoms/Button";
import { studentType } from "@/services/data-types/student-type";
import { studentService } from "@/services/student-service";

export default function Savings() {
  const [student, setStudent] = useState<studentType[]>([]);

  const getStudent = useCallback(async () => {
    setIsLoading(true);

    try {
      const response = await studentService();

      if (response.error) {
        alert(response.message);
      } else {
        setStudent(response.data);
      }
    } catch (error) {
      console.log(error);
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    getStudent();
  }, [getStudent]);

  const [isLoading, setIsLoading] = useState(false);
  const [savings, setSavings] = useState<savingType[]>([]);

  const getSaving = useCallback(async () => {
    setIsLoading(true);

    try {
      const response = await savingService();

      if (response.error) {
        alert(response.message);
      } else {
        setSavings(response.data);
      }
    } catch (error) {
      console.log(error);
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    getSaving();
  }, [getSaving]);

  return (
    <>
      <Head>
        <title>Admin Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="container-fluid px-4">
          <h1 className="mt-4">Savings</h1>
          <ol className="breadcrumb mb-4">
            <li className="breadcrumb-item active">Savings</li>
          </ol>
          <div className="card mb-4">
            <div className="card-header">
              <i className="fas fa-table me-1"></i>
              Data Savings{" "}
              <div className="d-flex justify-content-end gap-1">
                <Button
                  type="button"
                  onClickButton={getSaving}
                  isLoading={isLoading}
                  className={["btn btn-primary btn-sm"]}
                >
                  <i className="fas fa-sync-alt me-1"></i>
                </Button>
                <Button
                  type="link"
                  href="/saving/create"
                  className={["btn btn-primary btn-sm me-2"]}
                >
                  Tambah Data
                </Button>
              </div>
            </div>
            <div className="card-body">
              <table className="table">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Tanggal</th>
                    <th scope="col">Nis</th>
                    <th scope="col">Nama Siswa</th>
                    <th scope="col">Setor</th>
                    <th scope="col">Tarik</th>
                    <th scope="col">Jenis</th>
                    <th scope="col">Action</th>
                  </tr>
                </thead>
                <tbody>
                  {savings.map((item: savingType, index) => (
                    <tr key={index}>
                      <th scope="row">{index + 1}</th>
                      <td>{item.tgl}</td>
                      {student.map((student) => (
                        <td>{student.nis}</td>
                      ))}
                      {student.map((student) => (
                        <td>{student.nama_siswa}</td>
                      ))}
                      <td>Rp {item.setor.toLocaleString()}</td>
                      <td>Rp {item.tarik.toLocaleString()}</td>
                      <td>{item.jenis}</td>
                      <td>
                        <Button
                          type="link"
                          href={`saving/edit/${item.id}`}
                          className={["btn btn-warning btn-sm me-2"]}
                        >
                          Update
                        </Button>
                        <Button
                          type="link"
                          href={`saving/delete/${item.id}`}
                          className={["btn btn-danger btn-sm me-2"]}
                        >
                          delete
                        </Button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </Layout>
    </>
  );
}
