import Button from "@/components/atoms/Button";
import Layout from "@/components/organisms/Layout";
import { gradeType } from "@/services/data-types/grade-type";
<<<<<<< HEAD
import { savingServiceStore } from "@/services/grade-service";
import React, { useState } from "react";

export default function CreateGrade() {
  const [datas, setDatas] = useState<gradeType>({
    grade: "",
  });
  const [isLoading, setIsLoading] = useState(false);
  const [isError, setIsError] = useState({
    grade: "",
  });

  const onSubmit = async () => {
    setIsLoading(true);

    try {
      const data = new FormData();
      data.append("grade", datas.grade);

      const response = await savingServiceStore(data);

      if (!response.error) {
        alert("Grade created successfully");
      } else {
        if (response.message) {
          Object.entries(response.message).forEach(([key, value]) => {
            if (Array.isArray(value)) {
              setIsError({ ...isError, [key]: "is-invalid" });
              alert(value[0]);
            }
          });
        }
      }
    } catch (error) {
      alert((error as Error).message);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <>
      <Layout>
        <div className="container-fluid px-4">
          <h1 className="mt-4">Grade</h1>
          <ol className="breadcrumb mb-4">
            <li className="breadcrumb-item">Grade</li>
            <li className="breadcrumb-item active">Tambah data</li>
          </ol>

          <div className="card mb-4">
            <div className="card-header">
              <i className="fas fa-table me-1"></i>
              Form Input Grade
            </div>
            <div className="card-body">
              <form action="">
                <div className="row">
                  <div className="col-sm-6 mb-4">
                    <div className="mb-3">
                      <label htmlFor="inputGrade" className="form-label">
                        Grade
                      </label>
                      <input
                        type="text"
                        className={`form-control ${isError.grade}`}
                        id="inputGrade"
                        placeholder="Masukkan Grade"
                        value={datas.grade}
                        onChange={(e) =>
                          setDatas({ ...datas, grade: e.target.value })
                        }
                      />
                    </div>
                  </div>
                </div>
                <div className="d-flex">
                  <Button
                    type="button"
                    onClickButton={onSubmit}
                    isLoading={isLoading}
                    className={["btn btn-primary btn-sm me-2"]}
                  >
                    Simpan
                  </Button>
                  <Button
                    type="link"
                    href="/grade"
                    className={["btn btn-secondary btn-sm"]}
                  >
                    Kembali
                  </Button>
                </div>
              </form>
=======
import { gradeService } from "@/services/grade-service";
import Head from "next/head";
import React, { useCallback, useEffect, useState } from "react";

export default function Grades() {
  const [isLoading, setIsLoading] = useState(false);
  const [users, setUsers] = useState<gradeType[]>([]);

  const getUser = useCallback(async () => {
    setIsLoading(true);

    try {
      const response = await gradeService();

      if (response.error) {
        alert(response.message);
      } else {
        setUsers(response.data);
      }
    } catch (error) {
      console.log(error);
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    getUser();
  }, [getUser]);

  return (
    <>
      <Head>
        <title>Admin Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="container-fluid px-4">
          <h1 className="mt-4">Users</h1>
          <ol className="breadcrumb mb-4">
            <li className="breadcrumb-item active">Users</li>
          </ol>
          <div className="card mb-4">
            <div className="card-header">
              <i className="fas fa-table me-1"></i>
              Data Users{" "}
              <div className="d-flex justify-content-end gap-1">
                <Button
                  type="button"
                  onClickButton={getUser}
                  isLoading={isLoading}
                  className={["btn btn-primary btn-sm"]}
                >
                  <i className="fas fa-sync-alt me-1"></i>
                </Button>
                <Button
                  type="link"
                  href="/user/create"
                  className={["btn btn-primary btn-sm me-2"]}
                >
                  Tambah Data
                </Button>
              </div>
            </div>
            <div className="card-body">
              <table className="table">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Grade</th>
                    <th scope="col">Action</th>
                  </tr>
                </thead>
                <tbody>
                  {users.map((item: gradeType, index) => (
                    <tr key={index}>
                      <th scope="row">{index + 1}</th>
                      <td>{item.grade}</td>
                      <td>
                        <Button
                          type="button"
                          // onClickButton={
                          //   () => handleDetail(item.id)
                          // }
                          className={["btn btn-success btn-sm me-2"]}
                        >
                          Detail
                        </Button>
                        <Button
                          type="link"
                          href={`user/edit/${item.id}`}
                          className={["btn btn-warning btn-sm me-2"]}
                        >
                          Update
                        </Button>
                        <Button
                          type="link"
                          // onClickButton={
                          //   () => handleDetele(item.id)
                          // }
                          className={["btn btn-danger btn-sm me-2"]}
                        >
                          delete
                        </Button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
>>>>>>> f612f76790c9a3384613714ad532a3ed8011098f
            </div>
          </div>
        </div>
      </Layout>
    </>
  );
}
